BEGIN;

CREATE TABLE IF NOT EXISTS "SW_ships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "class" TEXT,
  "silhouette" INTEGER,
  "speed" INTEGER,
  "handling" INTEGER,
  "armor" INTEGER,
  "hull_trauma_threshold" INTEGER NOT NULL DEFAULT 0,
  "system_strain_threshold" INTEGER NOT NULL DEFAULT 0,
  "description" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sw_ships_hull_threshold_nonnegative CHECK ("hull_trauma_threshold" >= 0),
  CONSTRAINT sw_ships_system_threshold_nonnegative CHECK ("system_strain_threshold" >= 0)
);

CREATE TABLE IF NOT EXISTS "SW_character_ships" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "characterID" BIGINT NOT NULL,
  "shipID" BIGINT NOT NULL,
  "hull_trauma_current" INTEGER NOT NULL DEFAULT 0,
  "system_strain_current" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sw_character_ships_hull_current_nonnegative CHECK ("hull_trauma_current" >= 0),
  CONSTRAINT sw_character_ships_system_current_nonnegative CHECK ("system_strain_current" >= 0)
);

ALTER TABLE "SW_character_ships"
  ADD COLUMN IF NOT EXISTS "notes" TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_ships_character_fk'
  ) THEN
    ALTER TABLE "SW_character_ships"
      ADD CONSTRAINT sw_character_ships_character_fk
      FOREIGN KEY ("characterID") REFERENCES "SW_player_characters"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_ships_ship_fk'
  ) THEN
    ALTER TABLE "SW_character_ships"
      ADD CONSTRAINT sw_character_ships_ship_fk
      FOREIGN KEY ("shipID") REFERENCES "SW_ships"("id") ON DELETE RESTRICT;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_sw_character_ships_unique_character_ship
  ON "SW_character_ships" ("characterID", "shipID");

CREATE INDEX IF NOT EXISTS idx_sw_character_ships_character
  ON "SW_character_ships" ("characterID");

CREATE INDEX IF NOT EXISTS idx_sw_character_ships_ship
  ON "SW_character_ships" ("shipID");

-- Ensure ship catalog is readable by frontend clients.
ALTER TABLE "SW_ships" ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE "SW_ships" TO anon;
GRANT SELECT ON TABLE "SW_ships" TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_ships'
      AND policyname = 'sw_ships_select_public'
  ) THEN
    CREATE POLICY sw_ships_select_public
      ON "SW_ships"
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;
END $$;

-- Allow frontend clients to read/write character-owned ship rows.
ALTER TABLE "SW_character_ships" ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_ships" TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_ships" TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_character_ships'
      AND policyname = 'sw_character_ships_rw_public'
  ) THEN
    CREATE POLICY sw_character_ships_rw_public
      ON "SW_character_ships"
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

COMMIT;
