BEGIN;

ALTER TABLE "SW_equipment"
  ADD COLUMN IF NOT EXISTS "customization_hard_points" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "SW_ships"
  ADD COLUMN IF NOT EXISTS "customization_hard_points" INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'SW_equipment'
      AND column_name = 'HP'
  ) THEN
    EXECUTE '
      UPDATE "SW_equipment"
      SET "customization_hard_points" = GREATEST(0, COALESCE("HP", 0))
      WHERE COALESCE("customization_hard_points", 0) = 0
        AND "HP" IS NOT NULL
    ';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'SW_ships'
      AND column_name = 'HP'
  ) THEN
    EXECUTE '
      UPDATE "SW_ships"
      SET "customization_hard_points" = GREATEST(0, COALESCE("HP", 0))
      WHERE COALESCE("customization_hard_points", 0) = 0
        AND "HP" IS NOT NULL
    ';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_equipment_customization_hard_points_nonnegative'
  ) THEN
    ALTER TABLE "SW_equipment"
      ADD CONSTRAINT sw_equipment_customization_hard_points_nonnegative
      CHECK ("customization_hard_points" >= 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_ships_customization_hard_points_nonnegative'
  ) THEN
    ALTER TABLE "SW_ships"
      ADD CONSTRAINT sw_ships_customization_hard_points_nonnegative
      CHECK ("customization_hard_points" >= 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "SW_hardpoint_mod_catalog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "hp_cost" INTEGER NOT NULL DEFAULT 1,
  "applies_to" TEXT NOT NULL DEFAULT 'both',
  "user_id" BIGINT,
  "is_custom" BOOLEAN NOT NULL DEFAULT FALSE,
  "description" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sw_hardpoint_mod_catalog_hp_cost_positive CHECK ("hp_cost" > 0),
  CONSTRAINT sw_hardpoint_mod_catalog_applies_to_valid CHECK ("applies_to" IN ('weapon', 'armour', 'ship', 'both')),
  CONSTRAINT sw_hardpoint_mod_catalog_name_unique UNIQUE ("name")
);

ALTER TABLE "SW_hardpoint_mod_catalog"
  ADD COLUMN IF NOT EXISTS "user_id" BIGINT;

ALTER TABLE "SW_hardpoint_mod_catalog"
  ADD COLUMN IF NOT EXISTS "is_custom" BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
  IF to_regclass('public."SW_hardpoint_mod_catalog"') IS NOT NULL
    AND EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_hardpoint_mod_catalog_applies_to_valid'
      AND conrelid = to_regclass('public."SW_hardpoint_mod_catalog"')
  ) THEN
    ALTER TABLE "SW_hardpoint_mod_catalog"
      DROP CONSTRAINT sw_hardpoint_mod_catalog_applies_to_valid;
  END IF;

  ALTER TABLE "SW_hardpoint_mod_catalog"
    ADD CONSTRAINT sw_hardpoint_mod_catalog_applies_to_valid
    CHECK ("applies_to" IN ('weapon', 'armour', 'ship', 'both'));
END $$;

INSERT INTO "SW_hardpoint_mod_catalog" ("name", "hp_cost", "applies_to", "description")
VALUES
  ('Beam Splitter', 3, 'weapon', 'Converts fire to damage multiple targets at the cost of accuracy.'),
  ('Augmented Spin Barrel', 2, 'weapon', 'Increases the weapon range.'),
  ('Blaster Actuating Module', 1, 'weapon', 'Increases base damage and adds piercing capabilities.'),
  ('Custom Grip', 1, 'weapon', 'Removes setback dice from combat checks.'),
  ('Laser Sight', 1, 'weapon', 'Grants advantage on successful attacks.'),
  ('Marksman Barrel', 2, 'weapon', 'Extends weapon range and improves accuracy.'),
  ('Multi-Optic Sight', 1, 'weapon', 'Improves accuracy at long ranges.'),
  ('Weapon Sling / Harness', 2, 'weapon', 'Reduces encumbrance and makes the weapon easier to carry.'),
  ('Shock Pulse Emitter', 2, 'weapon', 'Adds stun quality to melee or brawl weapons.'),
  ('Armor Spikes', 1, 'armour', 'Adds melee defensive capabilities.'),
  ('Electro-binoculars (Integrated)', 1, 'armour', 'Built-in zoom and targeting assistance.'),
  ('Personal Deflector Shield', 2, 'armour', 'Provides a boost to defense and soak values.'),
  ('Vacuum Seals', 1, 'armour', 'Protects the wearer from hostile atmospheric environments.'),
  ('Advanced Shields', 2, 'ship', 'Upgrades shield output and improves defensive resilience.'),
  ('Enhanced Thrusters', 1, 'ship', 'Improves maneuverability and acceleration in flight.'),
  ('Improved Sensor Suite', 1, 'ship', 'Expands detection range and targeting support.'),
  ('Expanded Cargo Hold', 1, 'ship', 'Increases cargo and storage flexibility.'),
  ('Reinforced Hull Plating', 2, 'ship', 'Adds extra structural protection to the ship hull.'),
  ('Docking Clamps', 1, 'ship', 'Allows secure external cargo or craft attachment.')
ON CONFLICT ("name") DO UPDATE
SET
  "hp_cost" = EXCLUDED."hp_cost",
  "applies_to" = EXCLUDED."applies_to",
  "description" = EXCLUDED."description",
  "updated_at" = NOW();

CREATE TABLE IF NOT EXISTS "SW_character_equipment_hardpoint_mods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_equipment_id" BIGINT NOT NULL,
  "character_id" BIGINT NOT NULL,
  "user_id" BIGINT,
  "mod_id" BIGINT,
  "mod_name" TEXT NOT NULL,
  "hp_cost" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sw_character_equipment_hardpoint_mods_hp_cost_positive CHECK ("hp_cost" > 0)
);

CREATE TABLE IF NOT EXISTS "SW_character_ship_hardpoint_mods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_ship_id" BIGINT NOT NULL,
  "character_id" BIGINT NOT NULL,
  "user_id" BIGINT,
  "mod_id" BIGINT,
  "mod_name" TEXT NOT NULL,
  "hp_cost" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT sw_character_ship_hardpoint_mods_hp_cost_positive CHECK ("hp_cost" > 0)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_equipment_hardpoint_mods_character_equipment_fk'
  ) THEN
    ALTER TABLE "SW_character_equipment_hardpoint_mods"
      ADD CONSTRAINT sw_character_equipment_hardpoint_mods_character_equipment_fk
      FOREIGN KEY ("character_equipment_id") REFERENCES "SW_character_equipment"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_ship_hardpoint_mods_character_ship_fk'
  ) THEN
    ALTER TABLE "SW_character_ship_hardpoint_mods"
      ADD CONSTRAINT sw_character_ship_hardpoint_mods_character_ship_fk
      FOREIGN KEY ("character_ship_id") REFERENCES "SW_character_ships"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_ship_hardpoint_mods_character_fk'
  ) THEN
    ALTER TABLE "SW_character_ship_hardpoint_mods"
      ADD CONSTRAINT sw_character_ship_hardpoint_mods_character_fk
      FOREIGN KEY ("character_id") REFERENCES "SW_player_characters"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_ship_hardpoint_mods_catalog_fk'
  ) THEN
    ALTER TABLE "SW_character_ship_hardpoint_mods"
      ADD CONSTRAINT sw_character_ship_hardpoint_mods_catalog_fk
      FOREIGN KEY ("mod_id") REFERENCES "SW_hardpoint_mod_catalog"("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_equipment_hardpoint_mods_character_fk'
  ) THEN
    ALTER TABLE "SW_character_equipment_hardpoint_mods"
      ADD CONSTRAINT sw_character_equipment_hardpoint_mods_character_fk
      FOREIGN KEY ("character_id") REFERENCES "SW_player_characters"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sw_character_equipment_hardpoint_mods_catalog_fk'
  ) THEN
    ALTER TABLE "SW_character_equipment_hardpoint_mods"
      ADD CONSTRAINT sw_character_equipment_hardpoint_mods_catalog_fk
      FOREIGN KEY ("mod_id") REFERENCES "SW_hardpoint_mod_catalog"("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sw_character_equipment_hardpoint_mods_character_equipment
  ON "SW_character_equipment_hardpoint_mods" ("character_equipment_id");

CREATE INDEX IF NOT EXISTS idx_sw_character_equipment_hardpoint_mods_character
  ON "SW_character_equipment_hardpoint_mods" ("character_id");

CREATE INDEX IF NOT EXISTS idx_sw_character_ship_hardpoint_mods_character_ship
  ON "SW_character_ship_hardpoint_mods" ("character_ship_id");

CREATE INDEX IF NOT EXISTS idx_sw_character_ship_hardpoint_mods_character
  ON "SW_character_ship_hardpoint_mods" ("character_id");

ALTER TABLE "SW_hardpoint_mod_catalog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SW_character_equipment_hardpoint_mods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SW_character_ship_hardpoint_mods" ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_hardpoint_mod_catalog" TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_hardpoint_mod_catalog" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_equipment_hardpoint_mods" TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_equipment_hardpoint_mods" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_ship_hardpoint_mods" TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "SW_character_ship_hardpoint_mods" TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_hardpoint_mod_catalog'
      AND policyname = 'sw_hardpoint_mod_catalog_select_public'
  ) THEN
    CREATE POLICY sw_hardpoint_mod_catalog_select_public
      ON "SW_hardpoint_mod_catalog"
      FOR SELECT
      TO anon, authenticated
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_hardpoint_mod_catalog'
      AND policyname = 'sw_hardpoint_mod_catalog_rw_public'
  ) THEN
    CREATE POLICY sw_hardpoint_mod_catalog_rw_public
      ON "SW_hardpoint_mod_catalog"
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_character_equipment_hardpoint_mods'
      AND policyname = 'sw_character_equipment_hardpoint_mods_rw_public'
  ) THEN
    CREATE POLICY sw_character_equipment_hardpoint_mods_rw_public
      ON "SW_character_equipment_hardpoint_mods"
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'SW_character_ship_hardpoint_mods'
      AND policyname = 'sw_character_ship_hardpoint_mods_rw_public'
  ) THEN
    CREATE POLICY sw_character_ship_hardpoint_mods_rw_public
      ON "SW_character_ship_hardpoint_mods"
      FOR ALL
      TO anon, authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

COMMIT;
