-- Solo Adventures configurable choose-your-own-path schema
-- Run this in Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS "Solo_Adventures" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" TEXT NOT NULL,
  "Description" TEXT,
  "TTRPG" BIGINT,
  "Created_By" BIGINT,
  "Is_Published" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Solo_Adventure_Nodes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Adventure_ID" BIGINT NOT NULL,
  "Node_Title" TEXT,
  "Node_Content" TEXT NOT NULL,
  "Display_Order" INTEGER NOT NULL DEFAULT 0,
  "Is_Start" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Solo_Adventure_Choices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Node_ID" BIGINT NOT NULL,
  "Choice_Text" TEXT NOT NULL,
  "Next_Node_ID" BIGINT,
  "Check_Enabled" BOOLEAN NOT NULL DEFAULT FALSE,
  "Check_Skill" TEXT,
  "Check_Difficulty" INTEGER NOT NULL DEFAULT 0,
  "Check_Failure_Next_Node_ID" BIGINT,
  "Display_Order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "Solo_Adventure_Choices"
  ADD COLUMN IF NOT EXISTS "Check_Enabled" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "Check_Skill" TEXT,
  ADD COLUMN IF NOT EXISTS "Check_Difficulty" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Check_Failure_Next_Node_ID" BIGINT;

CREATE TABLE IF NOT EXISTS "Solo_Adventure_Runs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Adventure_ID" BIGINT NOT NULL,
  "Node_ID" BIGINT,
  "Character_ID" BIGINT,
  "Character_Name" TEXT,
  "TTRPG" BIGINT,
  "User_ID" BIGINT,
  "Path" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "Completed" BOOLEAN NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_nodes_adventure_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Nodes"
      ADD CONSTRAINT solo_nodes_adventure_fk
      FOREIGN KEY ("Adventure_ID") REFERENCES "Solo_Adventures"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_choices_failure_next_node_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Choices"
      ADD CONSTRAINT solo_choices_failure_next_node_fk
      FOREIGN KEY ("Check_Failure_Next_Node_ID") REFERENCES "Solo_Adventure_Nodes"("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_choices_node_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Choices"
      ADD CONSTRAINT solo_choices_node_fk
      FOREIGN KEY ("Node_ID") REFERENCES "Solo_Adventure_Nodes"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_choices_next_node_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Choices"
      ADD CONSTRAINT solo_choices_next_node_fk
      FOREIGN KEY ("Next_Node_ID") REFERENCES "Solo_Adventure_Nodes"("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_runs_adventure_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Runs"
      ADD CONSTRAINT solo_runs_adventure_fk
      FOREIGN KEY ("Adventure_ID") REFERENCES "Solo_Adventures"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'solo_runs_node_fk'
  ) THEN
    ALTER TABLE "Solo_Adventure_Runs"
      ADD CONSTRAINT solo_runs_node_fk
      FOREIGN KEY ("Node_ID") REFERENCES "Solo_Adventure_Nodes"("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_solo_adventures_ttrpg ON "Solo_Adventures" ("TTRPG");
CREATE INDEX IF NOT EXISTS idx_solo_adventures_published ON "Solo_Adventures" ("Is_Published");
CREATE INDEX IF NOT EXISTS idx_solo_nodes_adventure ON "Solo_Adventure_Nodes" ("Adventure_ID");
CREATE INDEX IF NOT EXISTS idx_solo_nodes_start ON "Solo_Adventure_Nodes" ("Adventure_ID", "Is_Start");
CREATE INDEX IF NOT EXISTS idx_solo_choices_node ON "Solo_Adventure_Choices" ("Node_ID");
CREATE INDEX IF NOT EXISTS idx_solo_choices_next_node ON "Solo_Adventure_Choices" ("Next_Node_ID");
CREATE INDEX IF NOT EXISTS idx_solo_choices_check_enabled ON "Solo_Adventure_Choices" ("Check_Enabled");
CREATE INDEX IF NOT EXISTS idx_solo_runs_user ON "Solo_Adventure_Runs" ("User_ID");
CREATE INDEX IF NOT EXISTS idx_solo_runs_character ON "Solo_Adventure_Runs" ("Character_ID");
CREATE INDEX IF NOT EXISTS idx_solo_runs_adventure ON "Solo_Adventure_Runs" ("Adventure_ID");

COMMIT;
