-- DND campaign tables (SW-style campaign flow with DND NPC stats)
-- Run this in Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS "DND_campaign" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" TEXT NOT NULL,
  "description" TEXT,
  "playerID" BIGINT,
  "TTRPG" BIGINT,
  "campaign_code" TEXT UNIQUE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "DND_campaign_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaignID" BIGINT NOT NULL,
  "Log" TEXT,
  "Log_number" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "DND_campaign_notes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CampaignID" BIGINT NOT NULL,
  "Place_Name" TEXT NOT NULL,
  "Description" TEXT,
  "Part_of_Place" BIGINT,
  "Order" INTEGER NOT NULL DEFAULT 1,
  "PictureID" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "DND_campaign_NPC" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CampaignID" BIGINT NOT NULL,
  "Part_of_Place" BIGINT,
  "Name" TEXT NOT NULL,
  "Race" BIGINT,
  "Description" TEXT,
  "PictureID" BIGINT,
  "Strength" INTEGER,
  "Dexterity" INTEGER,
  "Constitution" INTEGER,
  "Intelligence" INTEGER,
  "Wisdom" INTEGER,
  "Charisma" INTEGER,
  "Skills" TEXT,
  "Abilities" TEXT,
  "Equipment" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "DND_campaign_pictures" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_ID" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE "DND_player_character"
  ADD COLUMN IF NOT EXISTS "campaign_joined" BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_campaign_log_campaign_fk'
  ) THEN
    ALTER TABLE "DND_campaign_log"
      ADD CONSTRAINT dnd_campaign_log_campaign_fk
      FOREIGN KEY ("campaignID") REFERENCES "DND_campaign"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_campaign_notes_campaign_fk'
  ) THEN
    ALTER TABLE "DND_campaign_notes"
      ADD CONSTRAINT dnd_campaign_notes_campaign_fk
      FOREIGN KEY ("CampaignID") REFERENCES "DND_campaign"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_campaign_npc_campaign_fk'
  ) THEN
    ALTER TABLE "DND_campaign_NPC"
      ADD CONSTRAINT dnd_campaign_npc_campaign_fk
      FOREIGN KEY ("CampaignID") REFERENCES "DND_campaign"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_campaign_npc_race_fk'
  ) THEN
    ALTER TABLE "DND_campaign_NPC"
      ADD CONSTRAINT dnd_campaign_npc_race_fk
      FOREIGN KEY ("Race") REFERENCES "DND_Races"("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_player_character_campaign_joined_fk'
  ) THEN
    ALTER TABLE "DND_player_character"
      ADD CONSTRAINT dnd_player_character_campaign_joined_fk
      FOREIGN KEY ("campaign_joined") REFERENCES "DND_campaign"("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_dnd_campaign_player ON "DND_campaign" ("playerID");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_ttrpg ON "DND_campaign" ("TTRPG");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_code ON "DND_campaign" ("campaign_code");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_log_campaign ON "DND_campaign_log" ("campaignID");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_notes_campaign ON "DND_campaign_notes" ("CampaignID");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_notes_parent ON "DND_campaign_notes" ("Part_of_Place");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_npc_campaign ON "DND_campaign_NPC" ("CampaignID");
CREATE INDEX IF NOT EXISTS idx_dnd_campaign_npc_place ON "DND_campaign_NPC" ("Part_of_Place");
CREATE INDEX IF NOT EXISTS idx_dnd_player_character_campaign_joined ON "DND_player_character" ("campaign_joined");

COMMIT;
