-- Save slots for solo adventure progress.
-- Tracks user, adventure, character, and last page reached.

create table if not exists public."Solo_Adventure_Saves" (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  adventure_id bigint not null,
  character_id bigint not null,
  ttrpg_id bigint,
  current_page_id bigint,
  character_name text,
  adventure_title text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'solo_adventure_saves_user_id_fkey'
  ) then
    alter table public."Solo_Adventure_Saves"
      add constraint solo_adventure_saves_user_id_fkey
      foreign key (user_id)
      references public."user"(id)
      on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'solo_adventure_saves_adventure_id_fkey'
  ) then
    alter table public."Solo_Adventure_Saves"
      add constraint solo_adventure_saves_adventure_id_fkey
      foreign key (adventure_id)
      references public."Solo_Adventures"(id)
      on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'solo_adventure_saves_current_page_id_fkey'
  ) then
    alter table public."Solo_Adventure_Saves"
      add constraint solo_adventure_saves_current_page_id_fkey
      foreign key (current_page_id)
      references public."Solo_Adventure_Pages"(id)
      on delete set null;
  end if;
end $$;

create unique index if not exists idx_solo_adventure_saves_unique_slot
  on public."Solo_Adventure_Saves"(user_id, adventure_id, character_id);

create index if not exists idx_solo_adventure_saves_user_id
  on public."Solo_Adventure_Saves"(user_id);

create index if not exists idx_solo_adventure_saves_updated_at
  on public."Solo_Adventure_Saves"(updated_at desc);
