-- World Wide Wrestling (WWW) configurable system schema
-- Run this in Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS "WWW_Classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ClassName" TEXT NOT NULL,
  "Description" TEXT,
  "TTRPGs" TEXT
);

CREATE TABLE IF NOT EXISTS "WWW_CustomFields" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FieldName" TEXT NOT NULL,
  "FieldType" TEXT NOT NULL DEFAULT 'text',
  "FieldOptions" TEXT,
  "Required" BOOLEAN NOT NULL DEFAULT FALSE,
  "DisplayOrder" INTEGER NOT NULL DEFAULT 0,
  "Description" TEXT,
  "TTRPGs" TEXT
);

CREATE TABLE IF NOT EXISTS "WWW_player_characters" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "class_id" BIGINT,
  "class_name" TEXT,
  "custom_values" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "notes" TEXT,
  "TTRPG" BIGINT,
  "User_ID" BIGINT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'www_player_characters_class_fk'
  ) THEN
    ALTER TABLE "WWW_player_characters"
      ADD CONSTRAINT www_player_characters_class_fk
      FOREIGN KEY ("class_id") REFERENCES "WWW_Classes"("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_www_classes_ttrpgs ON "WWW_Classes" ("TTRPGs");
CREATE INDEX IF NOT EXISTS idx_www_fields_ttrpgs ON "WWW_CustomFields" ("TTRPGs");
CREATE INDEX IF NOT EXISTS idx_www_player_characters_ttrpg ON "WWW_player_characters" ("TTRPG");
CREATE INDEX IF NOT EXISTS idx_www_player_characters_user ON "WWW_player_characters" ("User_ID");

COMMIT;
