-- DND Character Creator schema expansion
-- Run this in Supabase SQL Editor.

BEGIN;

CREATE TABLE IF NOT EXISTS "DND_Races" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RaceName" TEXT NOT NULL,
  "DNDMod" TEXT,
  "Description" TEXT,
  "Size" TEXT,
  "Speed" INTEGER,
  "Languages" TEXT,
  "Traits" TEXT,
  "AbilityBonus_Str" INTEGER DEFAULT 0,
  "AbilityBonus_Dex" INTEGER DEFAULT 0,
  "AbilityBonus_Con" INTEGER DEFAULT 0,
  "AbilityBonus_Int" INTEGER DEFAULT 0,
  "AbilityBonus_Wis" INTEGER DEFAULT 0,
  "AbilityBonus_Cha" INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "DND_Backgrounds" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BackgroundName" TEXT NOT NULL,
  "DNDMod" TEXT,
  "Description" TEXT,
  "SkillProficiencies" TEXT,
  "ToolProficiencies" TEXT,
  "Languages" TEXT,
  "FeatureName" TEXT,
  "FeatureText" TEXT,
  "StartingEquipment" TEXT
);

CREATE TABLE IF NOT EXISTS "DND_Equipment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ItemName" TEXT NOT NULL,
  "DNDMod" TEXT,
  "Category" TEXT,
  "Description" TEXT,
  "Cost" TEXT,
  "Weight" TEXT,
  "Properties" TEXT,
  "Damage" TEXT,
  "DamageType" TEXT,
  "ArmorClass" TEXT,
  "AllowedClasses" TEXT
);

CREATE TABLE IF NOT EXISTS "DND_Spells" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SpellName" TEXT NOT NULL,
  "DNDMod" TEXT,
  "SpellLevel" INTEGER DEFAULT 0,
  "School" TEXT,
  "CastingTime" TEXT,
  "Range" TEXT,
  "Components" TEXT,
  "Duration" TEXT,
  "Description" TEXT,
  "ClassList" TEXT
);

ALTER TABLE "DND_player_character"
  ADD COLUMN IF NOT EXISTS "Race" BIGINT,
  ADD COLUMN IF NOT EXISTS "Background" BIGINT,
  ADD COLUMN IF NOT EXISTS "Alignment" TEXT,
  ADD COLUMN IF NOT EXISTS "Experience" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "MaxHP" INTEGER,
  ADD COLUMN IF NOT EXISTS "CurrentHP" INTEGER,
  ADD COLUMN IF NOT EXISTS "TempHP" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "ArmorClass" INTEGER,
  ADD COLUMN IF NOT EXISTS "InitiativeBonus" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Speed" INTEGER,
  ADD COLUMN IF NOT EXISTS "Inspiration" BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "PassivePerception" INTEGER DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "Inventory" TEXT,
  ADD COLUMN IF NOT EXISTS "Known_Equipment" TEXT,
  ADD COLUMN IF NOT EXISTS "Known_Spells" TEXT,
  ADD COLUMN IF NOT EXISTS "PersonalityTraits" TEXT,
  ADD COLUMN IF NOT EXISTS "Ideals" TEXT,
  ADD COLUMN IF NOT EXISTS "Bonds" TEXT,
  ADD COLUMN IF NOT EXISTS "Flaws" TEXT,
  ADD COLUMN IF NOT EXISTS "Backstory" TEXT,
  ADD COLUMN IF NOT EXISTS "Character_Notes" TEXT,
  ADD COLUMN IF NOT EXISTS "Money_CP" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Money_SP" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Money_EP" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Money_GP" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "Money_PP" INTEGER DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_player_character_race_fk'
  ) THEN
    ALTER TABLE "DND_player_character"
      ADD CONSTRAINT dnd_player_character_race_fk
      FOREIGN KEY ("Race") REFERENCES "DND_Races"("id") ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dnd_player_character_background_fk'
  ) THEN
    ALTER TABLE "DND_player_character"
      ADD CONSTRAINT dnd_player_character_background_fk
      FOREIGN KEY ("Background") REFERENCES "DND_Backgrounds"("id") ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_dnd_races_mod ON "DND_Races" ("DNDMod");
CREATE INDEX IF NOT EXISTS idx_dnd_backgrounds_mod ON "DND_Backgrounds" ("DNDMod");
CREATE INDEX IF NOT EXISTS idx_dnd_equipment_mod ON "DND_Equipment" ("DNDMod");
CREATE INDEX IF NOT EXISTS idx_dnd_spells_mod ON "DND_Spells" ("DNDMod");
CREATE INDEX IF NOT EXISTS idx_dnd_player_character_race ON "DND_player_character" ("Race");
CREATE INDEX IF NOT EXISTS idx_dnd_player_character_background ON "DND_player_character" ("Background");

COMMIT;
