create table if not exists public.dnd_mod_skill_mappings (
  id bigint generated by default as identity primary key,
  DNDMod text not null,
  base_skill text not null,
  mapped_skill text not null,
  updated_by bigint null,
  updated_at timestamptz not null default now(),
  constraint dnd_mod_skill_mappings_unique unique (DNDMod, base_skill)
);

create index if not exists dnd_mod_skill_mappings_mod_idx
  on public.dnd_mod_skill_mappings (DNDMod);

create or replace function public.touch_dnd_mod_skill_mappings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.dnd_mod_skill_mappings') is not null then
    drop trigger if exists trg_touch_dnd_mod_skill_mappings_updated_at on public.dnd_mod_skill_mappings;
    create trigger trg_touch_dnd_mod_skill_mappings_updated_at
    before update on public.dnd_mod_skill_mappings
    for each row
    execute function public.touch_dnd_mod_skill_mappings_updated_at();
  end if;
end;
$$;
